# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  func_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black
          python -m pip install -r tests/requirements.txt
      
      - name: Lint tests source with flake8
        run: |
          flake8 ./tests --count --show-source --statistics
      
      - name: Lint tests source with black
        run: |
          black ./tests --check
      
      - name: Run tests
        run: pytest ./tests -s -v -n auto
